# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myaccoutsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 4, 5, 3, 9, 26, 355194, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
