# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import myaccoutsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccoutsite', '0006_auto_20160413_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='BFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=128, unique=True)),
                ('file_save', models.FileField(upload_to=myaccoutsite.models.user_directory_path)),
                ('date_create', models.DateTimeField()),
                ('date_modify', models.DateTimeField()),
                ('slug', models.SlugField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccoutsite.RFUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
