# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myaccoutsite', '0007_auto_20160511_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bfile',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bfile',
            name='date_modify',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
