# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myaccoutsite', '0008_auto_20160511_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=128)),
                ('parent_id', models.CharField(max_length=128)),
                ('child_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, unique=True)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccoutsite.RFUser')),
            ],
        ),
        migrations.AddField(
            model_name='bfile',
            name='folder',
            field=models.CharField(default='P0', max_length=128),
        ),
        migrations.AlterField(
            model_name='bfile',
            name='date_modify',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='folder',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccoutsite.Project'),
        ),
    ]
