# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myaccoutsite', '0009_auto_20160512_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='id',
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bfile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccoutsite.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='child_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myaccoutsite.Folder'),
        ),
    ]
