# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myaccoutsite', '0012_remove_folder_child_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myaccoutsite.Folder'),
        ),
    ]
