# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BpmnProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, unique=True)),
                ('file_save', models.FileField(upload_to='bpmn_files/')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2016, 4, 26, 7, 9, 43, 82978, tzinfo=utc), verbose_name='创建日期')),
                ('date_modify', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
        ),
    ]
