# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpmnproject',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 7, 10, 12, 462617, tzinfo=utc), verbose_name='创建日期'),
        ),
    ]
